# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4c9dc129e68b889d9a351e14d8e36a02"
name = "saku-link-in-bio"
handle = "saku-link-in-bio"
application_url = "https://diff-shelter-subdivision-livestock.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_files,write_online_store_navigation,read_online_store_navigation"

[auth]
redirect_urls = ["https://diff-shelter-subdivision-livestock.trycloudflare.com/auth/callback", "https://diff-shelter-subdivision-livestock.trycloudflare.com/auth/shopify/callback", "https://diff-shelter-subdivision-livestock.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://diff-shelter-subdivision-livestock.trycloudflare.com/a/saku"
subpath = "saku"
prefix = "a"

[pos]
embedded = false
