# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2b94f79e87ae864f86d54772206e0d2e"
name = "Saku Link In Bio"
handle = "saku-link-in-bio"
application_url = "https://saku-link-in-bio.fly.dev"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_files,write_online_store_navigation,read_online_store_navigation"

[auth]
redirect_urls = [
    "https://saku-link-in-bio.fly.dev/auth/callback",
    "https://saku-link-in-bio.fly.dev/auth/shopify/callback",
    "https://saku-link-in-bio.fly.dev/api/auth/callback",
]

[app_proxy]
url = "https://saku-link-in-bio.fly.dev/a/saku"
subpath = "saku"
prefix = "a"

[pos]
embedded = false
