# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "883a8181758bb6c5148e4ebe7752b51e"
extension_directories = [ ]
name = "saku-link-in-bio"
handle = "saku-link-in-bio"
application_url = "https://casino-celebrity-gig-vegetarian.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://casino-celebrity-gig-vegetarian.trycloudflare.com/auth/callback",
  "https://casino-celebrity-gig-vegetarian.trycloudflare.com/auth/shopify/callback",
  "https://casino-celebrity-gig-vegetarian.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
