version: '3.8'

services:
  # Shopify Link-in-Bio App
  sfy-link-in-bio-app:
    build:
      context: ../
      dockerfile: devops/sfy-link-in-bio-app/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env.local
    restart: unless-stopped
