# fly.toml app configuration file generated for saku-link-in-bio on 2025-06-23T07:03:21+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'saku-link-in-bio'
primary_region = 'fra'

[build]
dockerfile = 'Dockerfile'

[build.args]
# Set these via environment variables or modify directly (https://saku-link-in-bio.fly.dev/api):
# fly deploy --build-arg VITE_CLIENT_API_CORE_URL=https://api.saku.so
VITE_CLIENT_API_CORE_URL = 'https://saku-link-in-bio.fly.dev/api'

[env]
PORT = '3000'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
