app = 'saku-sfy-link-in-bio-app'
primary_region = 'fra'

[build]
dockerfile = 'Dockerfile'

[build.args]
# Set these via environment variables or modify directly (https://sfy-link-in-bio-app.saku.so/api):
# fly deploy --build-arg VITE_API_CORE_URL=https://api.saku.so
SHOPIFY_APP_URL = 'https://sfy-link-in-bio-app.saku.so'
VITE_API_CORE_URL = 'https://sfy-link-in-bio-app.saku.so/api'
VITE_POSTHOG_KEY = 'phc_iYM9sMuBXqRqNfOztyvR4Nyg1YOcibB6rVleQpssuhg'
VITE_POSTHOG_HOST = 'https://us.i.posthog.com'
VITE_MANTLE_APP_ID = 'f82ef0a0-6589-46d0-8b39-d4b020bcbbca'
VITE_CRISP_TOKEN = '7aee5709-263b-4455-8556-642ce3d791ef'

[env]
PORT = '3000'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '512mb'    # Min 512mb for our use case (usage can spike over 256mb)
cpu_kind = 'shared'
cpus = 1
