/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/shopify/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Shopify session
         * @description Store a new Shopify session from app installation or authentication
         */
        post: operations["createShopifySession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/shopify/session/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Shopify session by ID
         * @description Retrieve a specific Shopify session by its ID
         */
        get: operations["getShopifySession"];
        put?: never;
        post?: never;
        /**
         * Delete Shopify session
         * @description Remove a Shopify session by its ID
         */
        delete: operations["deleteShopifySession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/shopify/session/shop/{shopId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Shopify session by shop
         * @description Retrieve Shopify sessions for a specific shop domain
         */
        get: operations["getShopifySessionByShop"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check API health
         * @description Returns the current health status of the API
         */
        get: operations["checkHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get API info
         * @description Returns the current info of the API
         */
        get: operations["getInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shopify/redirect/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check URL redirect path availability
         * @description Checks if a URL path is available for creating a redirect by validating against reserved paths and existing redirects.
         */
        get: operations["checkUrlRedirectAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shopify/shop/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get shop overview including theme, social links, and best-selling products
         * @description Retrieves comprehensive shop overview including theme styling, social media links, and best-selling products for creating default templates
         */
        get: operations["getShopOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shopify/site": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List connected sites
         * @description Returns all sites that are connected to the authenticated Shopify shop.
         */
        get: operations["listShopifySites"];
        put?: never;
        /**
         * Create new site
         * @description Creates a new site in the workspace connected to the authenticated Shopify shop.
         */
        post: operations["createShopifySite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shopify/site/{siteId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update site content
         * @description Updates the content of a site connected to the authenticated Shopify shop.
         */
        put: operations["updateShopifySiteContent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shopify/site/shop/{shop}/{handle}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get site content by shop and handle */
        get: operations["getShopifySiteContentByShopAndHandle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shopify/ugc/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List files from media library
         * @description Retrieve a paginated list of files from the Shopify media library with optional filtering
         */
        get: operations["listUgcMediaFiles"];
        put?: never;
        /**
         * Create upload targets for files
         * @description Generate signed upload URLs for multiple user-generated content files
         */
        post: operations["createUgcUploadTargets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shopify/ugc/files/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit uploaded files to media library
         * @description Process uploaded files and add them to the Shopify media library
         */
        post: operations["submitUgcUploadedFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shopify/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get workspace info
         * @description Returns workspace information for the authenticated Shopify shop, including onboarding status.
         */
        get: operations["getShopifyWorkspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/site/{siteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get site by ID */
        get: operations["getSite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/site/{siteId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get site content */
        get: operations["getSiteContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/site/parse/external": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Parse external link-in-bio URL */
        get: operations["parseExternalSite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/site/workspace/{workspaceHandle}/{handle}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get site content by workspace handle and site handle */
        get: operations["getSiteContentByWorkspaceAndHandle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/site/{siteId}/node/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a specific node in a site */
        put: operations["updateSiteNode"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/url/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get metadata from URL
         * @description Fetches and extracts metadata from the provided URL including title, description, media URLs and icons
         */
        get: operations["getUrlMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhook/shopify/customers/data_request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Customer data request webhook
         * @description Receives webhook when customers request their data from a store owner
         */
        post: operations["handleCustomerDataRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhook/shopify/customers/redact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Customer data redaction webhook
         * @description Receives webhook when store owners request customer data deletion
         */
        post: operations["handleCustomerRedact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhook/shopify/shop/redact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Shop data redaction webhook
         * @description Receives webhook 48 hours after a store owner uninstalls the app
         */
        post: operations["handleShopRedact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhook/shopify/app/uninstalled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * App uninstalled webhook
         * @description Receives webhook immediately when a store owner uninstalls the app
         */
        post: operations["handleAppUninstalled"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhook/shopify/app/scopes_update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * App scopes update webhook
         * @description Receives webhook when app scopes are updated for a store
         */
        post: operations["handleAppScopesUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AppErrorDto: {
            /**
             * @description A URI reference that identifies the problem type.
             * @default about:blank
             * @example https://docs.example.com/errors/validation-error
             */
            type: string;
            /**
             * @description A short, human-readable summary of the problem type.
             * @example Validation failed for the request parameters.
             */
            title: string;
            /**
             * @description The HTTP status code for this occurrence of the problem.
             * @example 400
             */
            status: number;
            /**
             * @description A human-readable explanation specific to this error occurrence.
             * @example Field `email` must be a valid email address.
             */
            detail?: string;
            /**
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example /api/users/1234
             */
            instance?: string;
            /**
             * @description An application-specific error code, useful for client-side logic.
             * @example VALIDATION_ERROR
             */
            code?: string;
            /**
             * @description Extension member for additional error context (e.g., per-field validation).
             * @example [
             *       {
             *         "field": "email",
             *         "reason": "must be a valid email"
             *       },
             *       {
             *         "field": "password",
             *         "reason": "is required"
             *       }
             *     ]
             */
            errors?: {
                [key: string]: unknown;
            }[];
        };
        ShopifySessionDto: {
            /** @example my-shop.myshopify.com_987654321 */
            id: string;
            /** @example my-shop.myshopify.com */
            shop: string;
            /** @example  */
            state: string;
            /** @example true */
            isOnline: boolean;
            /** @example write_products,read_customers */
            scope: string;
            /**
             * Format: date-time
             * @example 2025-06-14T13:39:33.336Z
             */
            expires: string | null;
            /** @example shpat_def456...uvw012 */
            accessToken: string;
            onlineAccessInfo: {
                /** @example 86399 */
                expires_in?: number;
                /** @example write_products,read_customers */
                associated_user_scope?: string;
                /** @example session_token_hash_string */
                session?: string;
                account_number?: number | null;
                associated_user: {
                    /** @example 987654321 */
                    id: number;
                    /** @example John */
                    first_name: string;
                    /** @example Doe */
                    last_name: string;
                    /**
                     * Format: email
                     * @example john@example.com
                     */
                    email: string;
                    /** @example true */
                    account_owner: boolean;
                    /** @example en-US */
                    locale: string;
                    /** @example false */
                    collaborator: boolean;
                    /** @example true */
                    email_verified: boolean;
                };
            } | null;
        };
        SiteSummaryDto: {
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3
             */
            id: string;
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3
             */
            workspaceId: string;
            /** @example bio */
            handle: string;
            /** @example My Bio Site */
            displayName?: string;
            /**
             * Format: date-time
             * @example 2024-03-20T00:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2024-03-20T00:00:00Z
             */
            updatedAt: string;
        };
        FlatSiteContentDto: {
            [key: string]: unknown;
        };
        SiteDto: {
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3
             */
            id: string;
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3
             */
            workspaceId: string;
            /** @example bio */
            handle: string;
            /** @example My Bio Site */
            displayName?: string;
            /**
             * Format: date-time
             * @example 2024-03-20T00:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2024-03-20T00:00:00Z
             */
            updatedAt: string;
            content: components["schemas"]["FlatSiteContentDto"];
        };
        SubmitUploadedFileSuccessDto: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "SUCCESS";
            /** @example gid://shopify/MediaImage/12345678 */
            id: string;
            /** @example ugc_abc123def456 */
            uploadId: string;
        };
        SubmitUploadedFileErrorDto: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "ERROR";
            /** @example Failed to process file */
            error: string;
            /** @example ugc_abc123def456 */
            uploadId: string;
        };
        MediaFileDto: {
            /** @example gid://shopify/MediaImage/12345678 */
            id: string;
            /** @example Product lifestyle image */
            alt: string;
            /**
             * Format: date-time
             * @example 2024-01-15T10:30:00Z
             */
            createdAt: string;
            previewImage?: {
                id: string;
                /** Format: uri */
                url: string;
            };
            /** Format: uri */
            url: string;
            /** @example product-1.jpg */
            fileName: string;
            details: {
                /** @enum {string} */
                type: "image";
                id?: string;
                width?: number;
                height?: number;
            } | {
                /** @enum {string} */
                type: "video";
                width: number;
                height: number;
                format: string;
            } | {
                /** @enum {string} */
                type: "file";
                mimeType?: string;
            };
        };
        WorkspaceDto: {
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3
             */
            id: string;
            /** @example my-store.myshopify.com */
            handle: string;
            /** @example My Store */
            displayName?: string;
            /** @example https://cdn.shopify.com/logo.png */
            image?: string;
            /**
             * Format: date-time
             * @description When onboarding was completed. null if onboarding is needed.
             * @example 2024-03-20T00:00:00Z
             */
            onboardingCompletedAt: string | null;
            /**
             * Format: date-time
             * @example 2024-03-20T00:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2024-03-20T00:00:00Z
             */
            updatedAt: string;
        };
        NodeDto: {
            [key: string]: unknown;
        };
        UrlMetadataDto: {
            /**
             * Format: uri
             * @description The URL that was fetched
             * @example https://example.com
             */
            url: string;
            /**
             * @description The page title from meta tags or title tag
             * @example Example Page Title
             */
            title?: string;
            /**
             * @description The page description from meta tags
             * @example A brief description of the page content
             */
            description?: string;
            site?: {
                /**
                 * @description The name of the website
                 * @example Example Site
                 */
                name?: string;
                /**
                 * Format: uri
                 * @description URL to the site-wide video if available
                 * @example https://example.com/video
                 */
                video?: string;
            };
            media?: {
                /**
                 * Format: uri
                 * @description Primary image URL from og:image or similar tags
                 * @example https://example.com/image.jpg
                 */
                image?: string;
                /**
                 * Format: uri
                 * @description Primary video URL from og:video or similar tags
                 * @example https://example.com/video.mp4
                 */
                video?: string;
                /**
                 * Format: uri
                 * @description Primary audio URL if available
                 * @example https://example.com/audio.mp3
                 */
                audio?: string;
            };
            icons?: {
                /**
                 * Format: uri
                 * @description URL to the favicon
                 * @example https://example.com/favicon.ico
                 */
                favicon?: string;
                /**
                 * Format: uri
                 * @description URL to the touch icon (e.g. apple-touch-icon)
                 * @example https://example.com/apple-touch-icon.png
                 */
                touch?: string;
                /**
                 * Format: uri
                 * @description URL to the mask icon (e.g. Safari pinned tab)
                 * @example https://example.com/mask-icon.svg
                 */
                mask?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createShopifySession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ShopifySessionDto"];
            };
        };
        responses: {
            /** @description Session created successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    getShopifySession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopifySessionDto"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    deleteShopifySession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    getShopifySessionByShop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopifySessionDto"][];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    checkHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example Up
                         * @enum {string}
                         */
                        status: "Up" | "Down";
                        /** @example App is up and running */
                        message: string;
                        /** @example v1.0.0d */
                        version: string;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    getInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example v1.0.0d */
                        version: string;
                        /** @example https://api.saku.so */
                        url: string;
                        /** @example https://app.saku.so */
                        appUrl: string;
                        /** @example production */
                        env: string;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    checkUrlRedirectAvailability: {
        parameters: {
            query: {
                /** @description The URL path to check (must start with /) */
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Whether the URL path is available for redirect creation
                         * @example true
                         */
                        isAvailable: boolean;
                        /**
                         * @description Type of conflict if path is not available
                         * @enum {string|null}
                         */
                        conflictType: "reserved_path" | "existing_redirect" | null;
                        /** @description Human-readable explanation of why the path is not available */
                        conflictReason: string | null;
                        /** @description List of existing redirects that conflict with the requested path */
                        existingRedirects: {
                            /**
                             * @description Shopify redirect ID
                             * @example gid://shopify/UrlRedirect/12345
                             */
                            id: string;
                            /**
                             * @description The redirect path
                             * @example /my-custom-path
                             */
                            path: string;
                            /**
                             * @description The redirect target
                             * @example /products/my-product
                             */
                            target: string;
                        }[];
                        /**
                         * @description List of Shopify reserved paths when conflict type is reserved_path
                         * @example [
                         *       "/products",
                         *       "/collections",
                         *       "/pages"
                         *     ]
                         */
                        reservedPaths: string[];
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    getShopOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        shop: {
                            /** @example gid://shopify/Shop/123456789 */
                            id: string;
                            /** @example My Awesome Store */
                            name: string;
                            /** @example my-awesome-store.myshopify.com */
                            domain: string;
                            /** @example Premium products for everyone */
                            description?: string;
                            /**
                             * Format: uri
                             * @example https://cdn.shopify.com/logo.png
                             */
                            logo?: string;
                            /** @example USD */
                            currency: string;
                            /** @example US */
                            country: string;
                            /** @example EN */
                            language: string;
                        };
                        theme: {
                            /** @example gid://shopify/Theme/123456789 */
                            id: string;
                            /** @example Dawn */
                            name: string;
                            /** @example MAIN */
                            role: string;
                            colors: {
                                /**
                                 * @description Primary brand color
                                 * @example #121212
                                 */
                                primary: string;
                                /**
                                 * @description Secondary brand color
                                 * @example #666666
                                 */
                                secondary: string;
                                /**
                                 * @description Background color
                                 * @example #ffffff
                                 */
                                background: string;
                                /**
                                 * @description Text color
                                 * @example #121212
                                 */
                                text: string;
                                /**
                                 * @description Button color
                                 * @example #121212
                                 */
                                button: string;
                                /**
                                 * @description Button text color
                                 * @example #ffffff
                                 */
                                buttonText: string;
                            };
                            typography: {
                                /**
                                 * @description Heading font family
                                 * @example Assistant
                                 */
                                headingFont: string;
                                /**
                                 * @description Body font family
                                 * @example Assistant
                                 */
                                bodyFont: string;
                                /**
                                 * @description Heading font scale percentage
                                 * @example 100
                                 */
                                headingScale: number;
                                /**
                                 * @description Body font scale percentage
                                 * @example 100
                                 */
                                bodyScale: number;
                            };
                            layout: {
                                /**
                                 * @description Maximum page width in pixels
                                 * @example 1200
                                 */
                                pageWidth: number;
                                /**
                                 * @description Section spacing in pixels
                                 * @example 0
                                 */
                                spacing: number;
                                /**
                                 * @description Border radius in pixels
                                 * @example 0
                                 */
                                borderRadius: number;
                            };
                        };
                        socialLinks: {
                            /**
                             * @description Social media platform
                             * @example instagram
                             */
                            platform: string;
                            /**
                             * Format: uri
                             * @example https://instagram.com/shopname
                             */
                            url: string;
                            /** @example @shopname */
                            username?: string;
                        }[];
                        bestSellingProducts: {
                            /** @example gid://shopify/Product/123456789 */
                            id: string;
                            /** @example Premium T-Shirt */
                            title: string;
                            /** @example premium-t-shirt */
                            handle: string;
                            /**
                             * Format: uri
                             * @example https://cdn.shopify.com/image.jpg
                             */
                            featuredImage?: string;
                            /** @example $29.99 */
                            price: string;
                            priceRange?: {
                                /** @example $29.99 */
                                min: string;
                                /** @example $39.99 */
                                max: string;
                            };
                        }[];
                        stats: {
                            /**
                             * @description Total number of products
                             * @example 150
                             */
                            totalProducts: number;
                            /**
                             * @description Total number of collections
                             * @example 12
                             */
                            totalCollections: number;
                            /**
                             * @description Total number of orders
                             * @example 1250
                             */
                            totalOrders?: number;
                        };
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Failed to fetch shop overview */
                        error: string;
                    };
                };
            };
        };
    };
    listShopifySites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteSummaryDto"][];
                };
            };
        };
    };
    createShopifySite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description Site handle/slug
                     * @example bio
                     */
                    handle: string;
                    /**
                     * @description Human-friendly site name
                     * @example My Bio Site
                     */
                    displayName?: string;
                    content: components["schemas"]["FlatSiteContentDto"];
                    /**
                     * @description Whether to create a URL redirect for the site (defaults to true)
                     * @example true
                     */
                    createRedirect?: boolean | null;
                    /**
                     * @description If true and createRedirect is true, will override any existing redirect with the same path
                     * @example false
                     */
                    overrideRedirect?: boolean | null;
                };
            };
        };
        responses: {
            /** @description Successful response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteDto"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    updateShopifySiteContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Site ID */
                siteId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    content: components["schemas"]["FlatSiteContentDto"];
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteDto"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    getShopifySiteContentByShopAndHandle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Shop domain */
                shop: string;
                /** @description Site handle/slug */
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlatSiteContentDto"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    listUgcMediaFiles: {
        parameters: {
            query?: {
                /** @description Number of items to return (max 250) */
                first?: number;
                /** @description Cursor for pagination */
                after?: string;
                /** @description Field to sort results by */
                sortKey?: "CREATED_AT" | "FILENAME" | "ID" | "ORIGINAL_UPLOAD_SIZE" | "RELEVANCE" | "UPDATED_AT";
                /** @description Reverse the sort order (true for descending, false for ascending) */
                reverse?: boolean | null;
                /** @description Filter by file types. Can be specified multiple times for multiple types. */
                fileTypes?: ("IMAGE" | "VIDEO" | "FILE" | "MODEL_3D" | "EXTERNAL_VIDEO")[];
                /** @description Filter by filename */
                fileName?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        files: components["schemas"]["MediaFileDto"][];
                        pageInfo: {
                            hasNextPage: boolean;
                            endCursor?: string;
                        };
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    createUgcUploadTargets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    files: {
                        /** @example product-image.jpg */
                        filename: string;
                        /** @example image/jpeg */
                        mimeType: string;
                        /** @example 1024000 */
                        fileSize: number;
                        /**
                         * @example IMAGE
                         * @enum {string}
                         */
                        contentType: "IMAGE" | "VIDEO" | "FILE";
                    }[];
                };
            };
        };
        responses: {
            /** @description Successful response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        files: {
                            uploadTarget: {
                                /**
                                 * Format: uri
                                 * @example https://shopify-staged-uploads.storage.googleapis.com/
                                 */
                                url: string;
                                /**
                                 * Format: uri
                                 * @example https://cdn.shopify.com/s/files/1/0123/4567/files/image.jpg
                                 */
                                resourceUrl: string;
                                parameters: {
                                    /** @example key */
                                    name: string;
                                    /** @example tmp/ugc/abc123/image.jpg */
                                    value: string;
                                }[];
                            };
                            /** @example ugc_abc123def456 */
                            uploadId: string;
                            /**
                             * Format: date-time
                             * @example 2024-01-15T10:30:00Z
                             */
                            expiresAt: string;
                        }[];
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    submitUgcUploadedFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    files: {
                        /** @example ugc_abc123def456 */
                        uploadId: string;
                        /**
                         * Format: uri
                         * @example https://cdn.shopify.com/s/files/1/0123/4567/files/product-1.jpg
                         */
                        resourceUrl: string;
                        /** @example product-1.jpg */
                        filename: string;
                        /**
                         * @example IMAGE
                         * @enum {string}
                         */
                        contentType: "IMAGE" | "VIDEO" | "FILE";
                    }[];
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        files: (components["schemas"]["SubmitUploadedFileSuccessDto"] | components["schemas"]["SubmitUploadedFileErrorDto"])[];
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    getShopifyWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceDto"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    getSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Site ID */
                siteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteDto"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    getSiteContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Site ID */
                siteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlatSiteContentDto"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    parseExternalSite: {
        parameters: {
            query: {
                /** @description External link-in-bio URL to parse */
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example linkpop */
                        provider: string;
                        /** @example johndoe */
                        handle: string;
                        content: components["schemas"]["FlatSiteContentDto"];
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    getSiteContentByWorkspaceAndHandle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace handle */
                workspaceHandle: string;
                /** @description Site handle/slug */
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlatSiteContentDto"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    updateSiteNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Site ID */
                siteId: string;
                /** @description Node ID */
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NodeDto"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    getUrlMetadata: {
        parameters: {
            query: {
                /** @description The URL to fetch metadata from */
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UrlMetadataDto"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    handleCustomerDataRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example 954889 */
                    shop_id: number;
                    /** @example my-shop.myshopify.com */
                    shop_domain: string;
                    /** @example [
                     *       299938,
                     *       280263,
                     *       220458
                     *     ] */
                    orders_requested: number[];
                    customer: {
                        /** @example 191167 */
                        id: number;
                        /**
                         * Format: email
                         * @example john@example.com
                         */
                        email: string;
                        /** @example 555-625-1199 */
                        phone: string;
                    };
                    data_request: {
                        /** @example 9999 */
                        id: number;
                    };
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Data request webhook received and processed */
                        message: string;
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    handleCustomerRedact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example 954889 */
                    shop_id: number;
                    /** @example my-shop.myshopify.com */
                    shop_domain: string;
                    customer: {
                        /** @example 191167 */
                        id: number;
                        /**
                         * Format: email
                         * @example john@example.com
                         */
                        email: string;
                        /** @example 555-625-1199 */
                        phone: string;
                    };
                    /** @example [
                     *       299938,
                     *       280263,
                     *       220458
                     *     ] */
                    orders_to_redact: number[];
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Customer redaction webhook received and processed */
                        message: string;
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    handleShopRedact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example 954889 */
                    shop_id: number;
                    /** @example my-shop.myshopify.com */
                    shop_domain: string;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Shop redaction webhook received and processed */
                        message: string;
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    handleAppUninstalled: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example 548380009 */
                    id: number;
                    /** @example Super Toys */
                    name: string;
                    /**
                     * Format: email
                     * @example super@supertoys.com
                     */
                    email: string;
                    /** @example supertoys.com */
                    domain: string | null;
                    /** @example super-toys.myshopify.com */
                    myshopify_domain: string;
                    /** @example enterprise */
                    plan_name: string;
                    /** @example Shopify Plus */
                    plan_display_name: string;
                    /** @example US */
                    country_code: string;
                    /** @example USD */
                    currency: string;
                    /** @example (GMT-05:00) Eastern Time (US & Canada) */
                    timezone: string;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example App uninstalled webhook received and processed */
                        message: string;
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
    handleAppScopesUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example 548380009 */
                    id: number;
                    /** @example [
                     *       "read_products"
                     *     ] */
                    previous: string[];
                    /** @example [
                     *       "read_products",
                     *       "write_products"
                     *     ] */
                    current: string[];
                    /**
                     * Format: date-time
                     * @example 2024-06-25T00:00:00.000Z
                     */
                    updated_at: string;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example App scopes update webhook received and processed */
                        message: string;
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppErrorDto"];
                };
            };
        };
    };
}
