# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "261eeadf370db94ba2357924d18767bf"
name = "Saku Link In Bio"
handle = "saku-link-in-bio"
application_url = "https://sfy-link-in-bio-app.saku.so"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_files,write_online_store_navigation,read_online_store_navigation"

[auth]
redirect_urls = [
    "https://sfy-link-in-bio-app.saku.so/auth/callback",
    "https://sfy-link-in-bio-app.saku.so/auth/shopify/callback",
    "https://sfy-link-in-bio-app.saku.so/api/auth/callback",
]

[webhooks]
api_version = "2025-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/api/v1/webhook/shopify/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/api/v1/webhook/shopify/app/scopes_update"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request"]
uri = "/api/v1/webhook/shopify/customers/data_request"

[[webhooks.subscriptions]]
compliance_topics = ["customers/redact"]
uri = "/api/v1/webhook/shopify/customers/redact"

[[webhooks.subscriptions]]
compliance_topics = ["shop/redact"]
uri = "/api/v1/webhook/shopify/shop/redact"

[app_proxy]
url = "https://sfy-link-in-bio-app.saku.so/a/saku"
subpath = "saku"
prefix = "a"

[pos]
embedded = false

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
