# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4c9dc129e68b889d9a351e14d8e36a02"
name = "Saku Link In Bio (Local)"
handle = "saku-link-in-bio-local"
application_url = "https://tel-belfast-abstract-divorce.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_files,write_online_store_navigation,read_online_store_navigation"

[auth]
redirect_urls = ["https://tel-belfast-abstract-divorce.trycloudflare.com/auth/callback", "https://tel-belfast-abstract-divorce.trycloudflare.com/auth/shopify/callback", "https://tel-belfast-abstract-divorce.trycloudflare.com/api/auth/callback"]

[webhooks]
api_version = "2025-04"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/api/v1/webhook/shopify/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/api/v1/webhook/shopify/app/scopes_update"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request"]
uri = "/api/v1/webhook/shopify/customers/data_request"

[[webhooks.subscriptions]]
compliance_topics = ["customers/redact"]
uri = "/api/v1/webhook/shopify/customers/redact"

[[webhooks.subscriptions]]
compliance_topics = ["shop/redact"]
uri = "/api/v1/webhook/shopify/shop/redact"

[app_proxy]
url = "https://tel-belfast-abstract-divorce.trycloudflare.com/a/saku-local"
subpath = "saku-local"
prefix = "a"

[pos]
embedded = false

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
