# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2b94f79e87ae864f86d54772206e0d2e"
name = "Saku Link In Bio"
handle = "saku-link-in-bio"
application_url = "https://sfy-link-in-bio-app.saku.so"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
compliance_topics = [
    "customers/data_request",
    "customers/redact",
    "shop/redact",
]
uri = "/api/v1/webhook/shopify"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_files,write_online_store_navigation,read_online_store_navigation"

[auth]
redirect_urls = [
    "https://sfy-link-in-bio-app.saku.so/auth/callback",
    "https://sfy-link-in-bio-app.saku.so/auth/shopify/callback",
    "https://sfy-link-in-bio-app.saku.so/api/auth/callback",
]

[app_proxy]
url = "https://sfy-link-in-bio-app.saku.so/a/saku"
subpath = "saku"
prefix = "a"

[pos]
embedded = false
